ARCHS = arm64
TARGET = iphone:clang:latest:17.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = Week52ProAudit
Week52ProAudit_FILES = Week52ProAudit.c
Week52ProAudit_CFLAGS = -Oz -fvisibility=hidden

include $(THEOS_MAKE_PATH)/library.mk
