override iQTeleEnhancer_FILES := Tweak.m MxPresentation.m Translation13.m Translation13TextFix.m LayoutFix.m Polish.m
override iQTeleEnhancer_LDFLAGS := -Wl,-install_name,@rpath/Prism.dylib
include Makefile
