#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import <objc/runtime.h>
#import <stdatomic.h>

static NSString *const kVersion=@"0.5.1";
static NSString *const kReport=@"XLiquidGlassCommentsDirectionProbe.txt";
static IMP gSetContentOffset=NULL;
static IMP gSettingsSetup=NULL;
static IMP gSettingsWillAppear=NULL;
static _Atomic(bool) gActive=false;
static BOOL gArmed=NO;
static NSUInteger gSerial=0;
static CFTimeInterval gStart=0;
static NSString *gLast=nil;
static NSMutableArray<NSString *> *gEvents=nil;
static NSMapTable<UIScrollView *, NSMutableDictionary *> *gState=nil;

static NSString *ReportPath(void){NSString *d=NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES).firstObject ?: NSTemporaryDirectory();return [d stringByAppendingPathComponent:kReport];}
static BOOL IsComments(UIScrollView *v){if(![NSStringFromClass(v.class) isEqualToString:@"TFNTableView"])return NO;BOOL u=NO,c=NO;UIResponder *r=v;for(NSUInteger i=0;r&&i<40;i++,r=r.nextResponder){if([r isKindOfClass:UIViewController.class]){NSString *n=NSStringFromClass(r.class);if([n isEqualToString:@"T1URTViewController"])u=YES;if([n isEqualToString:@"T1ConversationContainerViewController"])c=YES;}}return u&&c;}
static NSUInteger FilterCount(CALayer *l){if(!l)return 0;NSUInteger n=0;@try{id f=[l valueForKey:@"filters"];if([f isKindOfClass:NSArray.class])n+=[f count];id b=[l valueForKey:@"backgroundFilters"];if([b isKindOfClass:NSArray.class])n+=[b count];id c=[l valueForKey:@"compositingFilter"];if(c)n++;}@catch(__unused NSException *e){}for(CALayer *s in l.sublayers)n+=FilterCount(s);return n;}
static UIView *AncestorNamed(UIView *v,NSString *name){for(UIView *x=v;x;x=x.superview)if([NSStringFromClass(x.class) isEqualToString:name])return x;return nil;}
static UIView *DescendantNamed(UIView *v,NSString *name){if([NSStringFromClass(v.class) isEqualToString:name])return v;for(UIView *s in v.subviews){UIView *f=DescendantNamed(s,name);if(f)return f;}return nil;}
static NSString *Snapshot(UIScrollView *t){UIView *treatment=DescendantNamed(t,@"XDesignSystem.ScrollEdgeTreatment");if(!treatment){for(UIView *s in t.subviews){treatment=DescendantNamed(s,@"XDesignSystem.ScrollEdgeTreatment");if(treatment)break;}}UIView *back=treatment?DescendantNamed(treatment,@"_TtCC5UIKit20ScrollEdgeEffectView12BackdropView"):nil;UIView *effect=treatment?DescendantNamed(treatment,@"_TtC5UIKit20ScrollEdgeEffectView"):nil;return [NSString stringWithFormat:@"offset=%.1f dragging=%d decel=%d tracking=%d treatment=%p effect=%p backdrop=%p filters treatment=%lu effect=%lu backdrop=%lu",t.contentOffset.y,t.dragging,t.decelerating,t.tracking,treatment,effect,back,(unsigned long)FilterCount(treatment.layer),(unsigned long)FilterCount(effect.layer),(unsigned long)FilterCount(back.layer)];}
static void AddEvent(NSString *kind,UIScrollView *t,CGFloat dy){if(!atomic_load(&gActive))return;double ts=CACurrentMediaTime()-gStart;[gEvents addObject:[NSString stringWithFormat:@"%7.3fs %@ dy=%+.2f %@",ts,kind,dy,Snapshot(t)]];}
static void HookSetContentOffset(id self,SEL cmd,CGPoint p){UIScrollView *t=(UIScrollView *)self;CGPoint old=t.contentOffset;if(gSetContentOffset)((void(*)(id,SEL,CGPoint))gSetContentOffset)(self,cmd,p);if(!atomic_load(&gActive)||![NSThread isMainThread]||!IsComments(t))return;CGFloat dy=p.y-old.y;CFTimeInterval now=CACurrentMediaTime();NSMutableDictionary *st=[gState objectForKey:t];if(!st){st=[@{@"dir":@0,@"last":@(now),@"moving":@NO} mutableCopy];[gState setObject:st forKey:t];}
NSInteger dir=(fabs(dy)<0.25)?0:(dy>0?1:-1);NSInteger prev=[st[@"dir"] integerValue];CFTimeInterval last=[st[@"last"] doubleValue];BOOL moving=[st[@"moving"] boolValue];if(dir!=0){if(!moving || now-last>0.12){AddEvent(@"SCROLL_START",t,dy);}else if(prev!=0&&dir!=prev){AddEvent(@"DIRECTION_CHANGE",t,dy);}st[@"dir"]=@(dir);st[@"moving"]=@YES;st[@"last"]=@(now);}else if(moving&&now-last>0.12){st[@"moving"]=@NO;AddEvent(@"SCROLL_STOP",t,dy);} }
static BOOL Hook(Class c,SEL s,IMP r,IMP *o){Method m=class_getInstanceMethod(c,s);if(!m)return NO;IMP cur=class_getMethodImplementation(c,s);if(cur==r)return YES;if(o&&!*o)*o=cur;class_replaceMethod(c,s,r,method_getTypeEncoding(m));return YES;}
static NSString *BuildReport(void){NSDictionary *i=NSBundle.mainBundle.infoDictionary;NSMutableString *r=[NSMutableString stringWithFormat:@"============================================================\nXLiquidGlass Comments Direction Probe %@ - captura #%lu\nApp: %@ build %@ | bundle=%@\nEventos=%lu\n============================================================\n",kVersion,(unsigned long)gSerial,i[@"CFBundleShortVersionString"]?:@"-",i[@"CFBundleVersion"]?:@"-",NSBundle.mainBundle.bundleIdentifier?:@"-",(unsigned long)gEvents.count];for(NSString *e in gEvents)[r appendFormat:@"%@\n",e];[r appendString:@"============================================================\n"];return r;}
static UIViewController *TopVC(void){UIWindow *w=nil;for(UIScene *s in UIApplication.sharedApplication.connectedScenes)if([s isKindOfClass:UIWindowScene.class])for(UIWindow *x in ((UIWindowScene *)s).windows)if(x.isKeyWindow){w=x;break;}UIViewController *v=w.rootViewController;while(1){UIViewController *n=v.presentedViewController;if(!n&&[v isKindOfClass:UINavigationController.class])n=((UINavigationController*)v).topViewController;if(!n&&[v isKindOfClass:UITabBarController.class])n=((UITabBarController*)v).selectedViewController;if(!n||n==v)break;v=n;}return v;}
static void Finish(void){if(!atomic_exchange(&gActive,false))return;gLast=BuildReport();[gLast writeToFile:ReportPath() atomically:YES encoding:NSUTF8StringEncoding error:nil];UIPasteboard.generalPasteboard.string=gLast;UIViewController *v=TopVC();if(v){UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Direction Probe" message:@"Captura concluida e copiada." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];[v presentViewController:a animated:YES completion:nil];}}
static void Begin(void){if(!gArmed)return;gArmed=NO;gSerial++;gEvents=[NSMutableArray array];gState=[NSMapTable weakToStrongObjectsMapTable];gStart=CACurrentMediaTime();atomic_store(&gActive,true);dispatch_after(dispatch_time(DISPATCH_TIME_NOW,15*NSEC_PER_SEC),dispatch_get_main_queue(),^{Finish();});}
@interface XDPVC:UITableViewController@end
@implementation XDPVC
-(instancetype)init{return [super initWithStyle:UITableViewStyleInsetGrouped];}
-(void)viewDidLoad{[super viewDidLoad];self.title=@"Direction Probe";}
-(NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return 2;}
-(NSString*)tableView:(UITableView*)t titleForFooterInSection:(NSInteger)s{return @"Volte aos comentarios e faca: parado -> deslize -> inverta -> inverta novamente. Repita por 15 s.";}
-(UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)p{UITableViewCell*c=[t dequeueReusableCellWithIdentifier:@"x"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"x"];c.textLabel.text=p.row?@"Copiar relatorio":@"Iniciar diagnostico";return c;}
-(void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)p{[t deselectRowAtIndexPath:p animated:YES];if(p.row){NSString*x=gLast.length?gLast:[NSString stringWithContentsOfFile:ReportPath() encoding:NSUTF8StringEncoding error:nil];if(x.length)UIPasteboard.generalPasteboard.string=x;return;}UIAlertController*a=[UIAlertController alertControllerWithTitle:@"Direction Probe" message:@"Voce tera 8 segundos. Depois alterne a direcao varias vezes por 15 segundos." preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"Cancelar" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"Comecar" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*x){gArmed=YES;dispatch_after(dispatch_time(DISPATCH_TIME_NOW,8*NSEC_PER_SEC),dispatch_get_main_queue(),^{Begin();});}]];[self presentViewController:a animated:YES completion:nil];}
@end
static BOOL HasEntry(NSArray*a){for(id x in a)if([x isKindOfClass:NSDictionary.class]&&[x[@"action"] isEqualToString:@"showXLiquidGlassDirectionProbe"])return YES;return NO;}
static void Inject(id c){NSArray*a=nil;@try{a=[c valueForKey:@"sections"];}@catch(__unused NSException*e){return;}if(![a isKindOfClass:NSArray.class]||HasEntry(a))return;NSMutableArray*m=[a mutableCopy];[m addObject:@{@"title":@"Direction Probe",@"subtitle":@"Inicio e troca de direcao nos comentarios",@"icon":@"arrow.up.arrow.down",@"action":@"showXLiquidGlassDirectionProbe"}];@try{[c setValue:[m copy] forKey:@"sections"];}@catch(__unused NSException*e){}}
static void SSetup(id s,SEL c){if(gSettingsSetup)((void(*)(id,SEL))gSettingsSetup)(s,c);Inject(s);}static void SWill(id s,SEL c,BOOL a){if(gSettingsWillAppear)((void(*)(id,SEL,BOOL))gSettingsWillAppear)(s,c,a);Inject(s);UITableView*t=nil;@try{t=[s valueForKey:@"tableView"];}@catch(__unused NSException*e){}[t reloadData];}
static void Show(id s,SEL c){if(![s isKindOfClass:UIViewController.class])return;UIViewController*v=s;XDPVC*p=[XDPVC new];if(v.navigationController)[v.navigationController pushViewController:p animated:YES];else[v presentViewController:[[UINavigationController alloc]initWithRootViewController:p] animated:YES completion:nil];}
static void Install(void){Class t=NSClassFromString(@"TFNTableView");if(t&&!gSetContentOffset)Hook(t,@selector(setContentOffset:),(IMP)HookSetContentOffset,&gSetContentOffset);Class s=NSClassFromString(@"ModernSettingsViewController");if(s){class_addMethod(s,NSSelectorFromString(@"showXLiquidGlassDirectionProbe"),(IMP)Show,"v@:");if(!gSettingsSetup)Hook(s,NSSelectorFromString(@"setupSections"),(IMP)SSetup,&gSettingsSetup);if(!gSettingsWillAppear)Hook(s,@selector(viewWillAppear:),(IMP)SWill,&gSettingsWillAppear);}}
__attribute__((constructor))static void Init(void){@autoreleasepool{NSLog(@"[XLiquidGlassCommentsDirectionProbe] %@ loaded",kVersion);for(NSNumber*d in @[@0.05,@0.2,@0.5,@1,@2,@4,@8])dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(d.doubleValue*NSEC_PER_SEC)),dispatch_get_main_queue(),^{Install();});}}
